### ISSUE TITLE
patient ids in P19 dataset

### ISSUE THREAD

**Issue by hojjatkarami** [Leezekun/ViTST#1]
Hello,

There are 40336 patients in P19 dataset, however, you have used only 38803 (based on RainDrop paper). it is not clear for me, which patients have you removed from the original dataset. Hence, the correspondence between the split ids (provided in RainDrop) and the original dataset is not clear for me.

could please elaborate on that?

**Comment by Leezekun** [comment]
Hi, we used the data processed by the Raindrop paper. In their paper, they mentioned that the samples with too short or too long time series are removed. If you need further clarification on what patients are removed from the original P19 dataset, I suggest reaching out to them directly for the information.
