### ISSUE TITLE
No such file or directory: '../../dataset/P19data/processed_data/ImageDict_list.npy'

### ISSUE THREAD

**Issue by koredebishi** [Leezekun/ViTST#17]
Hi, 

I used the datasets images from your shared drive, extracted and placed everything where they should be. I cd into the right folder and run this: sh vtcls_script.sh.

I got the error that the "ImageDict_list.npy files" is needed. Could you please share the "ImageDict_list.npy" for each dataset OR do I need to go over the processed datasets and have one generated for myself?

I am trying to replicate your result and I want to stay close to your approach as much as possible.

Thanks.

**Comment by koredebishi** [comment]
Hi, 

I was able to get the ImageDict from the processed dataset. 

thanks.

**Comment by quanli95** [comment]
@koredebishi @Leezekun 
Hi, I have the same issue here. Could you please tell me how to get ImageDict_list.npy? Are there an existing npy file? Thanks a lot!

**Comment by ind588** [comment]
@koredebishi @Leezekun@quanli95
Hey, I am facing the same issue, how did you guys get the ImageDict_list.npy? Could you please let me know I want to reproduce the paper results.  Thank you!
